### ISSUE TITLE
Android updater fails to promote build to production track if artifact was already uploaded

### ISSUE THREAD

**Issue by delroth** [dolphin-emu/sadm#183]
```
Feb 13 00:00:00 altair systemd[1]: Starting Android Play Store updater (beta -> production)...
Feb 13 00:00:07 altair android-updater[2768075]: Traceback (most recent call last):
Feb 13 00:00:07 altair android-updater[2768075]:   File "/nix/store/phb42swrq1fd2phpz3bfl9jzkqfj932z-android-updater/bin/.android-updater-wrapped", line 93, in <module>
Feb 13 00:00:07 altair android-updater[2768075]:     _upload_new_playstore_apk(play, args.package_name, args.playstore_track,
Feb 13 00:00:07 altair android-updater[2768075]:   File "/nix/store/phb42swrq1fd2phpz3bfl9jzkqfj932z-android-updater/bin/.android-updater-wrapped", line 51, in _upload_new_playstore_apk
Feb 13 00:00:07 altair android-updater[2768075]:     mimetype=_APK_MIME)).execute()
Feb 13 00:00:07 altair android-updater[2768075]:   File "/nix/store/9bkjan3wm2jk1sqx3r6dq60895ddcg31-python3.10-google-api-python-client-2.61.0/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
Feb 13 00:00:07 altair android-updater[2768075]:     return wrapped(*args, **kwargs)
Feb 13 00:00:07 altair android-updater[2768075]:   File "/nix/store/9bkjan3wm2jk1sqx3r6dq60895ddcg31-python3.10-google-api-python-client-2.61.0/lib/python3.10/site-packages/googleapiclient/http.py", line 938, in execute
Feb 13 00:00:07 altair android-updater[2768075]:     raise HttpError(resp, content, uri=self.uri)
Feb 13 00:00:07 altair android-updater[2768075]: googleapiclient.errors.HttpError: <HttpError 403 when requesting https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/org.dolphinemu.dolphinemu/edits/10547343839644832876/apks?alt=json&uploadType=media returned "APK specifies a version code that has already been used.". Details: "APK specifies a version code that has already been used.">
Feb 13 00:00:07 altair systemd[1]: android-updater-release.service: Main process exited, code=exited, status=1/FAILURE
Feb 13 00:00:07 altair systemd[1]: android-updater-release.service: Failed with result 'exit-code'.
Feb 13 00:00:07 altair systemd[1]: Failed to start Android Play Store updater (beta -> production).
```

**Comment by delroth** [comment]
Fixed by https://github.com/dolphin-emu/sadm/commit/66809bfb21d53d28145188ae85778ef7cbf4fd6f
